int db_update(int table_id, int64_t key, char* values, int trx_id);
int db_find(int table_id, int64_t key, char* ret_val, int trx_id);
int trx_begin(void);
int trx_commit(int trx_id);
int open_table(char* pathname);
int close_table(int table_id);
int shutdown_db();
int init_db (int buf_num);
int db_insert(int table_id, int64_t key, char* value);
int db_delete(int table_id, int64_t key);
